import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
	src: "../public/fonts/inter/InterVariable.woff2",
	variable: "--font-inter",
	weight: "100 200 300 400 500 600 700 800 900",
	style: "normal",
});

const openRunde = localFont({
	src: [
		{
			path: "../public/fonts/OpenRunde-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/OpenRunde-Medium.woff2",
			weight: "500",
			style: "medium",
		},
		{
			path: "../public/fonts/OpenRunde-SemiBold.woff2",
			weight: "600",
			style: "semibold",
		},
		{
			path: "../public/fonts/OpenRunde-Bold.woff2",
			weight: "700",
			style: "bold",
		},
	],
	variable: "--font-open-runde",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${openRunde.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
